version: '3.9'

services:
  api: &main_app
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    image: bs_custom_model_service:${BS_CUSTOM_MODEL_SERVICE_VERSION:-latest}
    restart: always
    env_file:
      - .env
    environment:
      BS_CUSTOM_MODEL_SERVICE_HOST: 0.0.0.0


